# Generated by Django 6.1.1 on 2026-10-09 18:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("club", "0012_season_sheet_managed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "raw_name",
                    models.CharField(
                        help_text="Как в таблице; регистр, пробелы и ё/е не важны.",
                        max_length=100,
                        unique=True,
                        verbose_name="имя в таблице",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="club.player",
                        verbose_name="игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "имя в таблице",
                "verbose_name_plural": "имена в таблице",
                "ordering": ["raw_name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("raw_name"),
                        name="playeralias_raw_name_ci_unique",
                    )
                ],
            },
        ),
    ]
