# Generated by Django 6.1.1 on 2026-10-09 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.BinaryField(verbose_name="файл")),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="загружено"
                    ),
                ),
                ("sheets", models.JSONField(default=list, verbose_name="листы")),
                (
                    "fetched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "таблица клуба",
                "verbose_name_plural": "таблица клуба",
            },
        ),
    ]
