# Generated by Django 6.1.1 on 2026-09-27 23:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("club", "0003_live_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="ключ запроса"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("seat", "за стол"),
                            ("rebuy", "ребай"),
                            ("addon_on", "аддон"),
                            ("addon_off", "аддон снят"),
                            ("eliminate", "выбыл"),
                            ("restore", "возвращён в игру"),
                            ("topup", "докупка"),
                            ("exit", "выход"),
                            ("return", "вернулся"),
                            ("stage", "смена этапа"),
                            ("start", "игра начата"),
                            ("finish", "игра завершена"),
                            ("cancel", "игра отменена"),
                        ],
                        max_length=10,
                        verbose_name="действие",
                    ),
                ),
                ("summary", models.CharField(max_length=200, verbose_name="описание")),
                ("before", models.JSONField(blank=True, null=True, verbose_name="было")),
                ("after", models.JSONField(blank=True, null=True, verbose_name="стало")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="когда")),
                ("undone_at", models.DateTimeField(blank=True, null=True, verbose_name="отменено")),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_actions",
                        to="club.game",
                        verbose_name="игра",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="club.result",
                        verbose_name="результат",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто",
                    ),
                ),
            ],
            options={
                "verbose_name": "действие за столом",
                "verbose_name_plural": "действия за столом",
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                [
                                    "seat",
                                    "rebuy",
                                    "addon_on",
                                    "addon_off",
                                    "eliminate",
                                    "restore",
                                    "topup",
                                    "exit",
                                    "return",
                                    "stage",
                                    "start",
                                    "finish",
                                    "cancel",
                                ],
                            )
                        ),
                        name="liveaction_kind_valid",
                    )
                ],
            },
        ),
    ]
