# Generated by Django 6.1.1 on 2026-09-28 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import live.models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0007_blind_structures"),
        ("live", "0002_game_cascade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlindTimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("structure_name", models.CharField(max_length=100, verbose_name="структура")),
                ("position", models.PositiveSmallIntegerField(verbose_name="уровень отсчёта")),
                ("started_at", models.DateTimeField(verbose_name="начало уровня отсчёта")),
                ("paused_at", models.DateTimeField(blank=True, null=True, verbose_name="пауза с")),
                (
                    "display_token",
                    models.CharField(
                        default=live.models.display_token,
                        max_length=64,
                        unique=True,
                        verbose_name="ключ ссылки на табло",
                    ),
                ),
            ],
            options={
                "verbose_name": "таймер блайндов",
                "verbose_name_plural": "таймеры блайндов",
            },
        ),
        migrations.CreateModel(
            name="TimerLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "small_blind",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="малый блайнд"),
                ),
                (
                    "big_blind",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="большой блайнд"
                    ),
                ),
                (
                    "ante",
                    models.PositiveIntegerField(
                        default=0, help_text="0: без анте.", verbose_name="анте"
                    ),
                ),
                ("minutes", models.PositiveSmallIntegerField(verbose_name="минут")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Только для перерыва, например «Перерыв · аддон».",
                        max_length=60,
                        verbose_name="название перерыва",
                    ),
                ),
                (
                    "addon_break",
                    models.BooleanField(default=False, verbose_name="перерыв на аддон"),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="порядок")),
            ],
            options={
                "verbose_name": "уровень игры",
                "verbose_name_plural": "уровни игры",
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="liveaction",
            name="liveaction_kind_valid",
        ),
        migrations.AlterField(
            model_name="liveaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("seat", "за стол"),
                    ("rebuy", "ребай"),
                    ("addon_on", "аддон"),
                    ("addon_off", "аддон снят"),
                    ("eliminate", "выбыл"),
                    ("restore", "возвращён в игру"),
                    ("topup", "докупка"),
                    ("exit", "выход"),
                    ("return", "вернулся"),
                    ("stage", "смена этапа"),
                    ("start", "игра начата"),
                    ("finish", "игра завершена"),
                    ("timer", "таймер подключён"),
                    ("pause", "таймер: пауза"),
                    ("resume", "таймер: пуск"),
                    ("level_next", "таймер: следующий уровень"),
                    ("level_prev", "таймер: предыдущий уровень"),
                    ("plus_min", "таймер: +1 минута"),
                    ("level_edit", "уровень изменён"),
                    ("level_add", "уровень добавлен"),
                    ("bulk_min", "минуты уровней"),
                    ("link", "новая ссылка на табло"),
                ],
                max_length=10,
                verbose_name="действие",
            ),
        ),
        migrations.AddConstraint(
            model_name="liveaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "seat",
                            "rebuy",
                            "addon_on",
                            "addon_off",
                            "eliminate",
                            "restore",
                            "topup",
                            "exit",
                            "return",
                            "stage",
                            "start",
                            "finish",
                            "timer",
                            "pause",
                            "resume",
                            "level_next",
                            "level_prev",
                            "plus_min",
                            "level_edit",
                            "level_add",
                            "bulk_min",
                            "link",
                        ],
                    )
                ),
                name="liveaction_kind_valid",
            ),
        ),
        migrations.AddField(
            model_name="blindtimer",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blind_timer",
                to="club.game",
                verbose_name="игра",
            ),
        ),
        migrations.AddField(
            model_name="timerlevel",
            name="timer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="live.blindtimer",
                verbose_name="таймер",
            ),
        ),
        migrations.AddConstraint(
            model_name="blindtimer",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="blindtimer_position_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="blindtimer",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_token", ""), _negated=True),
                name="blindtimer_token_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="timerlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("minutes__gte", 1)), name="live_timerlevel_minutes_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="timerlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("big_blind__gte", models.F("small_blind")),
                        ("big_blind__isnull", False),
                        ("small_blind__gte", 1),
                        ("small_blind__isnull", False),
                    ),
                    models.Q(
                        ("ante", 0),
                        ("big_blind__isnull", True),
                        ("small_blind__isnull", True),
                        models.Q(("label", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="live_timerlevel_level_or_break",
            ),
        ),
        migrations.AddConstraint(
            model_name="timerlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("addon_break", False), ("big_blind__isnull", True), _connector="OR"
                ),
                name="live_timerlevel_addon_is_a_break",
            ),
        ),
        migrations.AddConstraint(
            model_name="timerlevel",
            constraint=models.UniqueConstraint(
                fields=("timer", "position"), name="timerlevel_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="timerlevel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("addon_break", True)),
                fields=("timer",),
                name="timerlevel_one_addon_break",
            ),
        ),
        migrations.AddConstraint(
            model_name="timerlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="timerlevel_position_positive"
            ),
        ),
    ]
