# Generated by Django 6.1.1 on 2026-09-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_organizer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="live_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rebuys", "Этап 1: ребаи"),
                    ("addon", "Перерыв на аддон"),
                    ("final", "Финальный этап"),
                    ("cash", "Кэш-игра идёт"),
                ],
                default="",
                help_text="Пусто: игра завершена. Пока игра идёт, она не входит в статистику.",
                max_length=6,
                verbose_name="идёт сейчас",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="начало"),
        ),
        migrations.AddField(
            model_name="result",
            name="addon",
            field=models.BooleanField(blank=True, null=True, verbose_name="аддон"),
        ),
        migrations.AddField(
            model_name="result",
            name="out_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Кто когда вышел из-за стола: 1 = первым. Пусто: ещё играет.",
                null=True,
                verbose_name="порядок выхода",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="rebuys",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="ребаев"),
        ),
        migrations.AddField(
            model_name="season",
            name="addon_price",
            field=models.PositiveIntegerField(default=50, verbose_name="аддон, лей"),
        ),
        migrations.AddField(
            model_name="season",
            name="cash_step",
            field=models.PositiveIntegerField(default=50, verbose_name="шаг закупки в кэше, лей"),
        ),
        migrations.AddField(
            model_name="season",
            name="entry_price",
            field=models.PositiveIntegerField(default=100, verbose_name="вход в турнир, лей"),
        ),
        migrations.AddField(
            model_name="season",
            name="rebuy_minutes",
            field=models.PositiveSmallIntegerField(
                default=120,
                help_text="Для обратного отсчёта на экране игры. Ребаи закрывает организатор.",
                verbose_name="ребаи открыты, минут",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="rebuy_price",
            field=models.PositiveIntegerField(default=50, verbose_name="ребай, лей"),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("live_stage__in", ["", "rebuys", "addon", "final", "cash"])),
                name="game_live_stage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("live_stage", ""), ("started_at__isnull", False), _connector="OR"
                ),
                name="game_live_has_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("out_order__isnull", True), ("out_order__gte", 1), _connector="OR"
                ),
                name="result_out_order_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.UniqueConstraint(
                fields=("game", "out_order"), name="result_game_out_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("addon_price__gte", 1),
                    ("cash_step__gte", 1),
                    ("entry_price__gte", 1),
                    ("rebuy_minutes__gte", 1),
                    ("rebuy_price__gte", 1),
                ),
                name="season_live_prices_positive",
            ),
        ),
    ]
