# Generated by Django 6.1.1 on 2026-09-27 23:53

from django.db import migrations, models


def weights_for_paid_places(apps, schema_editor):
    """The default "3,2,1" fits three paid places; other seasons get n,...,2,1 so they validate."""
    Season = apps.get_model("club", "Season")
    for season in Season.objects.exclude(paid_places=3):
        weights = ",".join(str(weight) for weight in range(season.paid_places, 0, -1))
        Season.objects.filter(pk=season.pk).update(payout_weights=weights)


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0003_live_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="payout_round",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Выплаты округляются вниз до этого шага, остаток получает первое место.",
                verbose_name="округление выплат, лей",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="payout_weights",
            field=models.CharField(
                default="3,2,1",
                help_text="По одной доле на призовое место, через запятую: 3,2,1 делит банк 3:2:1.",
                max_length=100,
                verbose_name="доли призовых мест",
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.CheckConstraint(
                condition=models.Q(("payout_round__gte", 1)), name="season_payout_round_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.CheckConstraint(
                condition=models.Q(("payout_weights__regex", "^[1-9][0-9]*(,[1-9][0-9]*)*$")),
                name="season_payout_weights_format",
            ),
        ),
        migrations.RunPython(weights_for_paid_places, migrations.RunPython.noop),
    ]
