# Generated by Django 6.1.1 on 2026-09-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0004_payout_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="entry_price",
            field=models.PositiveIntegerField(default=50, verbose_name="вход в турнир, лей"),
        ),
    ]
