# Generated by Django 6.1.1 on 2026-09-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0005_entry_price_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="rebuy_minutes",
            field=models.PositiveSmallIntegerField(
                default=120,
                help_text=(
                    "Примерно столько обычно идёт этап 1. Только подсказка на экране игры: "
                    "ребаи закрывает организатор."
                ),
                verbose_name="ориентир для ребаев, минут",
            ),
        ),
    ]
