# Generated by Django 6.1.1 on 2026-09-28 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0006_rebuy_minutes_hint"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlindStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="название")),
            ],
            options={
                "verbose_name": "структура блайндов",
                "verbose_name_plural": "структуры блайндов",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="blindstructure_name_not_empty",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="season",
            name="default_blinds",
            field=models.ForeignKey(
                blank=True,
                help_text="Предлагается при старте турнира; у игры своя копия.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="club.blindstructure",
                verbose_name="структура блайндов",
            ),
        ),
        migrations.CreateModel(
            name="BlindLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "small_blind",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="малый блайнд"),
                ),
                (
                    "big_blind",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="большой блайнд"
                    ),
                ),
                (
                    "ante",
                    models.PositiveIntegerField(
                        default=0, help_text="0: без анте.", verbose_name="анте"
                    ),
                ),
                ("minutes", models.PositiveSmallIntegerField(verbose_name="минут")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Только для перерыва, например «Перерыв · аддон».",
                        max_length=60,
                        verbose_name="название перерыва",
                    ),
                ),
                (
                    "addon_break",
                    models.BooleanField(default=False, verbose_name="перерыв на аддон"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="порядок"
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="club.blindstructure",
                        verbose_name="структура",
                    ),
                ),
            ],
            options={
                "verbose_name": "уровень",
                "verbose_name_plural": "уровни и перерывы",
                "ordering": [models.OrderBy(models.F("position"), nulls_last=True), "pk"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("minutes__gte", 1)),
                        name="club_blindlevel_minutes_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("big_blind__gte", models.F("small_blind")),
                                ("big_blind__isnull", False),
                                ("small_blind__gte", 1),
                                ("small_blind__isnull", False),
                            ),
                            models.Q(
                                ("ante", 0),
                                ("big_blind__isnull", True),
                                ("small_blind__isnull", True),
                                models.Q(("label", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="club_blindlevel_level_or_break",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("addon_break", False), ("big_blind__isnull", True), _connector="OR"
                        ),
                        name="club_blindlevel_addon_is_a_break",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("addon_break", True)),
                        fields=("structure",),
                        name="blindlevel_one_addon_break",
                        violation_error_message=(
                            "Перерыв на аддон в структуре может быть только один."
                        ),
                    ),
                ],
            },
        ),
    ]
