# Generated by Django 6.1.1 on 2026-09-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0008_organizer_blind_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blindlevel",
            options={
                "ordering": [models.OrderBy(models.F("position"), nulls_last=True), "pk"],
                "verbose_name": "уровень или перерыв",
                "verbose_name_plural": "уровни и перерывы",
            },
        ),
    ]
