# Generated by Django 6.1.1 on 2026-09-29 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0009_blind_level_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "no_skip_min_evenings",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Месяц с меньшим числом клубных вечеров не считается.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="«Ни одного прогула»: минимум вечеров в месяце",
                    ),
                ),
                (
                    "always_itm_min_tournaments",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="«Всегда в деньгах»: минимум турниров за сезон",
                    ),
                ),
                (
                    "hat_trick_length",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Пропущенные турниры серию не прерывают.",
                        validators=[django.core.validators.MinValueValidator(2)],
                        verbose_name="хет-трик: призовых подряд",
                    ),
                ),
                (
                    "comeback_min_rebuys",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Считается по закупке: вход плюс столько ребаев или больше.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="камбэк: минимум ребаев",
                    ),
                ),
                (
                    "itm_series_steps",
                    models.CharField(
                        default="5,10",
                        help_text="Через запятую: 5,10 даёт грамоты за 5 и за 10 призовых подряд.",
                        max_length=60,
                        verbose_name="грамоты за призовые подряд",
                    ),
                ),
                (
                    "evening_series_steps",
                    models.CharField(
                        default="3,5,10",
                        help_text="Через запятую; пропущенный клубный вечер прерывает серию.",
                        max_length=60,
                        verbose_name="грамоты за вечера подряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "параметры наград",
                "verbose_name_plural": "параметры наград",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="achievementsettings_single_row"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("always_itm_min_tournaments__gte", 1),
                            ("comeback_min_rebuys__gte", 1),
                            ("hat_trick_length__gte", 2),
                            ("no_skip_min_evenings__gte", 1),
                        ),
                        name="achievementsettings_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("itm_series_steps__regex", "^[1-9][0-9]*(,[1-9][0-9]*)*$"),
                            ("evening_series_steps__regex", "^[1-9][0-9]*(,[1-9][0-9]*)*$"),
                        ),
                        name="achievementsettings_steps_format",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankLadder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("veteran", "Сыграно игр"),
                            ("feeder", "Сумма закупок, лей"),
                            ("addon", "Аддонов"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="счётчик",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="название")),
            ],
            options={
                "verbose_name": "лестница званий",
                "verbose_name_plural": "лестницы званий",
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__in", ["veteran", "feeder", "addon"])),
                        name="rankladder_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="rankladder_title_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        help_text="Звание даётся, когда счётчик игрока достигает порога.",
                        verbose_name="порог",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="звание")),
                (
                    "ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="club.rankladder",
                        verbose_name="лестница",
                    ),
                ),
            ],
            options={
                "verbose_name": "ступень",
                "verbose_name_plural": "ступени",
                "ordering": ["ladder", "threshold"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ladder", "threshold"),
                        name="rankstep_ladder_threshold_unique",
                        violation_error_message="На лестнице уже есть ступень с таким порогом.",
                    ),
                    models.UniqueConstraint(
                        fields=("ladder", "title"),
                        name="rankstep_ladder_title_unique",
                        violation_error_message="На этой лестнице уже есть такое звание.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("threshold__gte", 1)),
                        name="rankstep_threshold_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="rankstep_title_not_empty",
                    ),
                ],
            },
        ),
    ]
