# Generated by Django 6.1.1 on 2026-09-28 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_orphans(apps, schema_editor):
    """Rows left by cancelled games (game set to null): the game is gone, so is its log."""
    apps.get_model("live", "LiveAction").objects.filter(game__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0004_payout_split"),
        ("live", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First: the rows with a null game go (the cancel rows among them), then the field
        # becomes required and "cancel" leaves the kinds.
        migrations.RunPython(delete_orphans, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="liveaction",
            name="liveaction_kind_valid",
        ),
        migrations.AlterField(
            model_name="liveaction",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_actions",
                to="club.game",
                verbose_name="игра",
            ),
        ),
        migrations.AlterField(
            model_name="liveaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("seat", "за стол"),
                    ("rebuy", "ребай"),
                    ("addon_on", "аддон"),
                    ("addon_off", "аддон снят"),
                    ("eliminate", "выбыл"),
                    ("restore", "возвращён в игру"),
                    ("topup", "докупка"),
                    ("exit", "выход"),
                    ("return", "вернулся"),
                    ("stage", "смена этапа"),
                    ("start", "игра начата"),
                    ("finish", "игра завершена"),
                ],
                max_length=10,
                verbose_name="действие",
            ),
        ),
        migrations.AddConstraint(
            model_name="liveaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "seat",
                            "rebuy",
                            "addon_on",
                            "addon_off",
                            "eliminate",
                            "restore",
                            "topup",
                            "exit",
                            "return",
                            "stage",
                            "start",
                            "finish",
                        ],
                    )
                ),
                name="liveaction_kind_valid",
            ),
        ),
    ]
