# Generated by Django 6.1.1 on 2026-09-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                (
                    "nickname",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="ник"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        db_index=False,
                        help_text="Оставьте пустым, чтобы сгенерировать из ника или имени.",
                        max_length=120,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "игрок",
                "verbose_name_plural": "игроки",
                "ordering": ["name", "nickname"],
                "constraints": [
                    models.UniqueConstraint(fields=("slug",), name="player_slug_unique"),
                    models.UniqueConstraint(
                        fields=("name", "nickname"), name="player_name_nickname_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="player_name_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("slug", ""), _negated=True),
                        name="player_slug_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="год")),
                (
                    "kind",
                    models.CharField(
                        choices=[("tour", "Турнир"), ("cash", "Кэш")],
                        max_length=4,
                        verbose_name="тип",
                    ),
                ),
                (
                    "chips_per_lei",
                    models.PositiveIntegerField(default=100, verbose_name="фишек за 1 лей"),
                ),
                (
                    "paid_places",
                    models.PositiveSmallIntegerField(default=3, verbose_name="призовых мест"),
                ),
            ],
            options={
                "verbose_name": "сезон",
                "verbose_name_plural": "сезоны",
                "ordering": ["-year", "kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "kind"), name="season_year_kind_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["tour", "cash"])), name="season_kind_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chips_per_lei__gte", 1)),
                        name="season_chips_per_lei_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("paid_places__gte", 1)),
                        name="season_paid_places_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("year__gte", 2000), ("year__lte", 2100)),
                        name="season_year_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="дата")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="место проведения"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games",
                        to="club.season",
                        verbose_name="сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "игра",
                "verbose_name_plural": "игры",
                "ordering": ["-date", "season__kind"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("buyin", models.PositiveIntegerField(verbose_name="закупка")),
                ("payout", models.PositiveIntegerField(default=0, verbose_name="выплата")),
                (
                    "place",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="место"),
                ),
                (
                    "chips_out",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="фишек на выходе"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="club.game",
                        verbose_name="игра",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="club.player",
                        verbose_name="игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат",
                "verbose_name_plural": "результаты",
                "ordering": ["game", models.OrderBy(models.F("place"), nulls_last=True), "-payout"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "player"), name="result_game_player_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("buyin__gte", 1)), name="result_buyin_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("place__isnull", True), ("place__gte", 1), _connector="OR"
                        ),
                        name="result_place_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("place__isnull", True), ("chips_out__isnull", True), _connector="OR"
                        ),
                        name="result_place_xor_chips_out",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["date"], name="game_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("season", "date"), name="game_season_date_unique"
            ),
        ),
    ]
